language: node_js
node_js:
  - "stable"
env:
  global:
  - CC_TEST_REPORTER_ID=b7709add516697a075823b247bc611ccf7e9cd42733dcaa1f7d58147d6c1fc4c
cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test
  
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

